
# SEO settings
title: "4cyb3r"
title2: "Blog" # default: ""
description: "free thoughtfull from my mind"
keywords: ""
url: http://4cyb3r.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io
paginate: 10
paginate_path: "/page:num/"

google_analytics: UA-XXXXX-XX
repo: http://github.com/4cyb3r/4cyb3r.github.io
disqus_shortname: "4cyb3r"
twitter_username: ""
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Rakha F Maulana"
  job      : "IT Network System Administration"
  bio      : "nothing really necessary here, just a bunch of /tmp "
  thumb    : /images/author.jpg
  email    : 4cyb3r@gmail.com
  url      :  
  github   : http://github.com/4cyb3r
  twitter  : 
  facebook : 
  linkedin :  

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
